train: /kaggle/input/test-autoannotation/datset_yolo_annotation/coco_datset/train
val: /kaggle/input/test-autoannotation/datset_yolo_annotation/coco_datset/val
nc: 298
names:
  [
    "diaper",
    "dog collar",
    "reflector",
    "glasses",
    "umbrella",
    "traffic light",
    "tag",
    "suitcase",
    "skateboard",
    "power plugs and sockets",
    "hot dog",
    "kite",
    "pay phone",
    "blender",
    "headband",
    "silo",
    "airplane",
    "scarf",
    "poster",
    "prawn",
    "wheel",
    "grapefruit",
    "pear",
    "teddy bear",
    "support hose",
    "picnic basket",
    "candle",
    "cowboy hat",
    "bottle cap",
    "fireplace",
    "sweater",
    "shopping cart",
    "tennis racket",
    "wine glass",
    "ring",
    "tomato",
    "towel rack",
    "signboard",
    "ball",
    "necklace",
    "studio couch",
    "sandwich",
    "dolphin",
    "knob",
    "statue (sculpture)",
    "mousepad",
    "lamp",
    "billboard",
    "giraffe",
    "blackboard",
    "microwave oven",
    "fume hood",
    "cattle",
    "goggles",
    "cucumber",
    "light bulb",
    "dog",
    "vehicle registration plate",
    "swimwear",
    "glove",
    "door handle",
    "blanket",
    "cistern",
    "box",
    "cushion",
    "headlight",
    "bath mat",
    "stool",
    "man",
    "saucer",
    "knife",
    "carrot",
    "pillow",
    "toilet",
    "baseball glove",
    "bird",
    "houseplant",
    "mask",
    "visor",
    "computer monitor",
    "fire hydrant",
    "chandelier",
    "baseball base",
    "blueberry",
    "computer mouse",
    "sweatshirt",
    "fire alarm",
    "boy",
    "tank top",
    "piano",
    "fancy dress",
    "ski",
    "heart",
    "shower curtain",
    "camera",
    "bus",
    "candle holder",
    "flower",
    "bottle",
    "windmill",
    "paper towel",
    "cake",
    "apron",
    "bench",
    "street sign",
    "motor",
    "muffin",
    "miniskirt",
    "plastic bag",
    "mechanical fan",
    "oven",
    "egg",
    "pop bottle",
    "towel/napkin",
    "train",
    "computer keyboard",
    "button",
    "boat",
    "sunflower",
    "short pants",
    "pot/pan",
    "ski pole",
    "lampshade",
    "baseball bat",
    "crown",
    "sink",
    "book",
    "car",
    "corded phone",
    "adhesive tape",
    "coaster",
    "flag",
    "bathtub",
    "paddle",
    "taillight",
    "bread",
    "vestment",
    "cookie",
    "shorts",
    "bicycle",
    "girl",
    "onion",
    "headscarf",
    "trousers",
    "baseball cap",
    "vent",
    "serving tray",
    "coffee maker",
    "loudspeaker",
    "awning",
    "cabinetry",
    "curtain",
    "cauliflower",
    "buoy",
    "steering wheel",
    "surfboard",
    "tin can",
    "broccoli",
    "handbag",
    "frying pan",
    "coat",
    "bed",
    "backpack",
    "guitar",
    "parking meter",
    "building",
    "vehicle",
    "envelope",
    "bookcase",
    "chair",
    "doughnut",
    "potato",
    "magnet",
    "mobile phone",
    "painting",
    "tablecloth",
    "bracelet",
    "soap dispenser",
    "bolt",
    "coffee cup",
    "elephant",
    "windshield wiper",
    "laptop",
    "banner",
    "motorcycle",
    "sausage",
    "green beans",
    "clock tower",
    "beanie",
    "stop sign",
    "towel",
    "key",
    "mound (baseball)",
    "lettuce",
    "truck",
    "tinfoil",
    "saddle",
    "drinking straw",
    "bicycle wheel",
    "cherry",
    "balloon",
    "frisbee",
    "ski boot",
    "street light",
    "woman",
    "remote control",
    "rearview mirror",
    "wristlet",
    "wet suit",
    "toilet paper",
    "television",
    "log",
    "sock",
    "boot",
    "cupcake",
    "dishwasher",
    "jacket",
    "drawer",
    "hook",
    "hinge",
    "bucket",
    "cooler (for food)",
    "coffee table",
    "strawberry",
    "polo shirt",
    "tiara",
    "clock",
    "printer",
    "bear",
    "scissors",
    "footwear",
    "grapes",
    "fork",
    "bow (decorative ribbons)",
    "zebra",
    "bull mastiff",
    "house",
    "pen",
    "horse",
    "trash bin/can",
    "bath towel",
    "toaster",
    "sunglasses",
    "ladder",
    "belt",
    "flowerpot",
    "plate",
    "seahorse",
    "sheep",
    "barrel",
    "human face",
    "air conditioner",
    "pizza",
    "pineapple",
    "bell pepper",
    "apple",
    "earrings",
    "starfish",
    "suit",
    "tie",
    "scoreboard",
    "watch",
    "faucet",
    "knee pad",
    "land vehicle",
    "banana",
    "person",
    "bowl",
    "helmet",
    "desk",
    "toothbrush",
    "bib",
    "spoon",
    "toy",
    "refrigerator",
    "salt and pepper shakers",
    "swim cap",
    "lemon",
    "orange",
    "tower",
    "mirror",
    "headboard",
    "sandal",
    "kitchen & dining room table",
    "shower cap",
    "snowboard",
    "mushroom",
    "scone",
    "hat",
    "choker",
    "watermelon",
    "vase",
    "wheelchair",
    "propeller",
    "alarm clock",
    "chopping board",
    "cat",
    "microphone",
  ]
